name: ar_admin

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main , dev]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: moubarmijoun
          password: moubarmijoun.dev@gmail.com
      - name: check branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: moubarmijoun/promosport:ar_admin_${{ env.BRANCH }}
          build-args: |
                        BRANCH=${{ env.BRANCH }}
          push: true